name: Weed
favicon: null
layout_spectrum: 0.1699009481817484
typography_spectrum: 0.4734885466750711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9515084612648934
  lightness: 0.029810172971338034
  saturation: 0.8082970438990742
  rhythmicContrast: 0.8654282451607287
purpose: []
